# Generated by Django 4.2 on 2026-05-23 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0003_delete_alerts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ServerLog', to='system.server')),
            ],
        ),
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Error type')),
                ('admin_message', models.TextField(blank=True, null=True, verbose_name='admin message for the problem')),
                ('security', models.CharField(max_length=100, verbose_name='warning/critical')),
                ('resolved', models.CharField(max_length=50, verbose_name='solved or not')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='system.server')),
            ],
        ),
    ]
