# Generated by Django 4.2 on 2026-05-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='resolved',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='security',
            field=models.CharField(choices=[('None', 'None'), ('warning', 'warning'), ('critical', 'critical')], max_length=8, verbose_name='Security status'),
        ),
    ]
