# Generated by Django 4.2 on 2026-06-10 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_alerts_resolved_alter_alerts_security'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logs',
        ),
    ]
