# Generated by Django 4.2 on 2026-06-21 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alert_delete_alerts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'permissions': [('view_all_alerts', 'Can view all alerts'), ('manage_alerts', 'Can manage alerts')]},
        ),
    ]
