# Generated by Django 4.2 on 2026-06-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='created_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
