# Generated by Django 4.2 on 2026-06-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_logs_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='level',
            field=models.CharField(blank=True, choices=[('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR')], default='INFO', max_length=10, null=True),
        ),
    ]
