# Generated by Django 4.2 on 2026-06-10 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_alter_server_status'),
        ('logs', '0003_alter_logs_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='ServerLogs',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='logs',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='مogs', to='system.server'),
        ),
    ]
