# Generated by Django 4.2 on 2026-06-11 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_alter_server_status'),
        ('logs', '0004_rename_serverlogs_logs_message_alter_logs_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='system.server'),
        ),
    ]
