# Generated by Django 4.2 on 2026-06-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_alter_logs_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
