# Generated by Django 4.2 on 2026-06-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_alter_logs_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
