# Generated by Django 4.2 on 2026-06-21 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_alter_logs_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'permissions': [('view_all_logs', 'Can view all logs'), ('manage_logs', 'Can manage logs')]},
        ),
    ]
