# Generated by Django 4.2 on 2026-05-22 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=100)),
                ('ipaddress', models.GenericIPAddressField()),
                ('os', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('online', 'system online'), ('offline', 'system offline')], max_length=7)),
                ('lastseen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField(blank=True, verbose_name='Cpu Usage')),
                ('ram_usage', models.FloatField(blank=True, verbose_name='Ram Usage')),
                ('disk_usage', models.FloatField(blank=True, verbose_name='Disk Usage')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SystemStatus', to='system.server')),
            ],
        ),
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Error type')),
                ('admin_message', models.TextField(blank=True, null=True, verbose_name='admin message for the problem')),
                ('security', models.CharField(max_length=100, verbose_name='warning/critical')),
                ('resolved', models.CharField(max_length=50, verbose_name='solved or not')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='system.server')),
            ],
        ),
    ]
