# Generated by Django 4.2 on 2026-07-03 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import system.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('ipaddress', models.GenericIPAddressField()),
                ('os', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('online', 'system online'), ('offline', 'system offline')], default='offline', max_length=7)),
                ('lastseen', models.DateTimeField(auto_now=True)),
                ('agent_token', models.CharField(default=system.models.generate_token, max_length=64, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('view_all_servers', 'Can view all servers'), ('manage_servers', 'Can manage servers')],
            },
        ),
    ]
