# Generated by Django 4.2 on 2026-05-22 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemStatus',
        ),
    ]
