# Generated by Django 4.2 on 2026-05-23 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_delete_systemstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alerts',
        ),
    ]
