# Generated by Django 4.2 on 2026-06-01 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0006_alter_server_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server', to=settings.AUTH_USER_MODEL),
        ),
    ]
