# Generated by Django 4.2 on 2026-06-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_alter_server_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='agent_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
