# Generated by Django 4.2 on 2026-06-08 07:56

from django.db import migrations, models
import system.models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_server_agent_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='agent_token',
            field=models.CharField(default=system.models.generate_token, max_length=64, unique=True),
        ),
    ]
