# Generated by Django 4.2 on 2026-06-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_alter_server_agent_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.CharField(choices=[('online', 'system online'), ('offline', 'system offline')], default='offline', max_length=7),
        ),
    ]
