# Generated by Django 4.2 on 2026-06-21 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_alter_server_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'permissions': [('view_all_servers', 'Can view all servers'), ('manage_servers', 'Can manage servers')]},
        ),
    ]
