# Generated by Django 4.2 on 2026-06-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_alter_server_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='lastseen',
        ),
        migrations.AddField(
            model_name='server',
            name='create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
