# Generated by Django 4.2 on 2026-06-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_remove_server_lastseen_server_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='create',
        ),
        migrations.AddField(
            model_name='server',
            name='lastseen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
