# Generated by Django 4.2 on 2026-05-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerTables',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=100)),
                ('ipaddress', models.GenericIPAddressField()),
                ('os', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('online', 'system online'), ('offline', 'system offline')], max_length=7)),
                ('lastseen', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
