# Generated by Django 4.2 on 2026-07-03 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField(blank=True, default=0, null=True, verbose_name='Cpu Usage')),
                ('ram_usage', models.FloatField(blank=True, default=0, null=True, verbose_name='Ram Usage')),
                ('disk_usage', models.FloatField(blank=True, default=0, null=True, verbose_name='Disk Usage')),
                ('network_in', models.FloatField(blank=True, default=0, null=True, verbose_name='network_in')),
                ('network_out', models.FloatField(blank=True, default=0, null=True, verbose_name='network_out')),
                ('process_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='process_count')),
                ('uptime_seconds', models.BigIntegerField(blank=True, default=0, null=True)),
                ('lastupdate', models.DateTimeField(blank=True, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='system.server')),
            ],
            options={
                'permissions': [('view_all_statuses', 'Can view all statuses'), ('manage_statuses', 'Can manage statuses')],
            },
        ),
    ]
