# Generated by Django 4.2 on 2026-05-22 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0002_delete_systemstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField(blank=True, verbose_name='Cpu Usage')),
                ('ram_usage', models.FloatField(blank=True, verbose_name='Ram Usage')),
                ('disk_usage', models.FloatField(blank=True, verbose_name='Disk Usage')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SystemStatus', to='system.server')),
            ],
        ),
    ]
