# Generated by Django 4.2 on 2026-05-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemstatus',
            name='lastupdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemstatus',
            name='network_in',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='systemstatus',
            name='network_out',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='systemstatus',
            name='uptime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemstatus',
            name='cpu_usage',
            field=models.FloatField(blank=True, null=True, verbose_name='Cpu Usage'),
        ),
        migrations.AlterField(
            model_name='systemstatus',
            name='disk_usage',
            field=models.FloatField(blank=True, null=True, verbose_name='Disk Usage'),
        ),
        migrations.AlterField(
            model_name='systemstatus',
            name='ram_usage',
            field=models.FloatField(blank=True, null=True, verbose_name='Ram Usage'),
        ),
    ]
