# Generated by Django 4.2 on 2026-05-31 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_alter_server_user'),
        ('monitoring', '0002_systemstatus_lastupdate_systemstatus_network_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemstatus',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server', to='system.server'),
        ),
    ]
