# Generated by Django 4.2 on 2026-06-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_systemstatus_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemstatus',
            name='cpu_usage',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Cpu Usage'),
        ),
        migrations.AlterField(
            model_name='systemstatus',
            name='disk_usage',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Disk Usage'),
        ),
        migrations.AlterField(
            model_name='systemstatus',
            name='ram_usage',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Ram Usage'),
        ),
    ]
