# Generated by Django 4.2 on 2026-06-01 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_alter_server_user'),
        ('monitoring', '0005_alter_systemstatus_cpu_usage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemstatus',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='system.server'),
        ),
    ]
