# Generated by Django 4.2 on 2026-06-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_alter_server_user'),
        ('monitoring', '0006_alter_systemstatus_server'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SystemStatus',
            new_name='ServerStatus',
        ),
    ]
