# Generated by Django 4.2 on 2026-06-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_rename_systemstatus_serverstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstatus',
            name='network_in',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='network_in'),
        ),
        migrations.AlterField(
            model_name='serverstatus',
            name='network_out',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='network_out'),
        ),
    ]
