# Generated by Django 4.2 on 2026-06-21 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_alter_serverstatus_network_in_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverstatus',
            options={'permissions': [('view_all_statuses', 'Can view all statuses'), ('manage_statuses', 'Can manage statuses')]},
        ),
    ]
