# Generated by Django 4.2 on 2026-06-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_alter_serverstatus_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstatus',
            name='lastupdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
