# Generated by Django 4.2 on 2026-06-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_alter_serverstatus_lastupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstatus',
            name='lastupdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
