# Generated by Django 4.2 on 2026-06-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_alter_serverstatus_lastupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverstatus',
            name='process_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='process_count'),
        ),
    ]
