# Generated by Django 4.2 on 2026-06-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_serverstatus_process_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverstatus',
            name='uptime',
        ),
        migrations.AddField(
            model_name='serverstatus',
            name='uptime_seconds',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
